In [1]:
import pandas as pd
df = pd.read_csv('postings.csv', sep=',', header=None, na_values=[''], quotechar='"')
df

C:\Users\Anchal Singh\AppData\Local\Temp\ipykernel_25472\252585177.py:2: DtypeWarning: Columns (0: 0, 1: 4, 2: 7, 3: 8, 4: 9, 5: 10, 6: 12, 7: 13, 8: 14, 9: 18, 10: 19, 11: 22, 12: 24, 13: 28, 14: 29, 15: 30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('postings.csv', sep=',', header=None, na_values=[''], quotechar='"')

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
1,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1713397508000.0,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,08540,34021
2,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1712857887000.0,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521,08069
3,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1713277614000.0,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202,39061
4,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1712895812000.0,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040,36059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123845,3906267117,Lozano Smith,Title IX/Investigations Attorney,Our Walnut Creek office is currently seeking a...,195000.0,YEARLY,"Walnut Creek, CA",56120.0,1.0,NaN,...,NaN,1713571223000.0,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,94595.0,6013.0
123846,3906267126,Pinterest,"Staff Software Engineer, ML Serving Platform",About Pinterest:\n\nMillions of people across ...,NaN,NaN,United States,1124131.0,3.0,NaN,...,NaN,1713572236000.0,www.pinterestcareers.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123847,3906267131,EPS Learning,"Account Executive, Oregon/Washington",Company Overview\n\nEPS Learning is a leading ...,NaN,NaN,"Spokane, WA",90552133.0,3.0,NaN,...,NaN,1713572339000.0,epsoperations.bamboohr.com,0,FULL_TIME,NaN,NaN,NaN,99201.0,53063.0
123848,3906267195,Trelleborg Applied Technologies,Business Development Manager,The Business Development Manager is a 'hunter'...,NaN,NaN,"Texas, United States",2793699.0,4.0,NaN,...,NaN,1713572632000.0,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
123849,3906267224,Solugenix,Marketing Social Media Specialist,Marketing Social Media Specialist - $70k – $75...,75000.0,YEARLY,"San Juan Capistrano, CA",43325.0,2.0,NaN,...,NaN,1713572616000.0,NaN,0,FULL_TIME,USD,BASE_SALARY,72500.0,92675.0,6059.0

In [2]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
      dtype='int64')

In [4]:
jobs = pd.read_csv('jobs.csv', sep=',', na_values=[''], quotechar='"')
jobs

,title,max_salary,pay_period,location,views,min_salary,formatted_work_type,applies,original_listed_time,remote_allowed,application_type,expiry,formatted_experience_level,listed_time,work_type,currency,compensation_type,normalized_salary
0,Marketing Coordinator,20.0,HOURLY,"Princeton, NJ",20.0,17.0,Full-time,2.0,1.713400e+12,NaN,ComplexOnsiteApply,1.715990e+12,NaN,1.713400e+12,FULL_TIME,USD,BASE_SALARY,38480.0
1,Mental Health Therapist/Counselor,50.0,HOURLY,"Fort Collins, CO",1.0,30.0,Full-time,NaN,1.712860e+12,NaN,ComplexOnsiteApply,1.715450e+12,NaN,1.712860e+12,FULL_TIME,USD,BASE_SALARY,83200.0
2,Assitant Restaurant Manager,65000.0,YEARLY,"Cincinnati, OH",8.0,45000.0,Full-time,NaN,1.713280e+12,NaN,ComplexOnsiteApply,1.715870e+12,NaN,1.713280e+12,FULL_TIME,USD,BASE_SALARY,55000.0
3,Senior Elder Law / Trusts and Estates Associat...,175000.0,YEARLY,"New Hyde Park, NY",16.0,140000.0,Full-time,NaN,1.712900e+12,NaN,ComplexOnsiteApply,1.715490e+12,NaN,1.712900e+12,FULL_TIME,USD,BASE_SALARY,157500.0
4,Service Technician,80000.0,YEARLY,"Burlington, IA",3.0,60000.0,Full-time,NaN,1.713450e+12,NaN,ComplexOnsiteApply,1.716040e+12,NaN,1.713450e+12,FULL_TIME,USD,BASE_SALARY,70000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,Title IX/Investigations Attorney,195000.0,YEARLY,"Walnut Creek, CA",1.0,120000.0,Full-time,NaN,1.713570e+12,NaN,ComplexOnsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,USD,BASE_SALARY,157500.0
123845,"Staff Software Engineer, ML Serving Platform",NaN,NaN,United States,3.0,NaN,Full-time,NaN,1.713570e+12,1.0,OffsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,NaN,NaN,NaN
123846,"Account Executive, Oregon/Washington",NaN,NaN,"Spokane, WA",3.0,NaN,Full-time,NaN,1.713570e+12,1.0,OffsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,NaN,NaN,NaN
123847,Business Development Manager,NaN,NaN,"Texas, United States",4.0,NaN,Full-time,NaN,1.713570e+12,1.0,ComplexOnsiteApply,1.716160e+12,NaN,1.713570e+12,FULL_TIME,NaN,NaN,NaN
123848,Marketing Social Media Specialist,75000.0,YEARLY,"San Juan Capistrano, CA",2.0,70000.0,Full-time,NaN,1.713570e+12,NaN,ComplexOnsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,USD,BASE_SALARY,72500.0

In [5]:
jobs.columns

Index(['title', 'max_salary', 'pay_period', 'location', 'views', 'min_salary',
       'formatted_work_type', 'applies', 'original_listed_time',
       'remote_allowed', 'application_type', 'expiry',
       'formatted_experience_level', 'listed_time', 'work_type', 'currency',
       'compensation_type', 'normalized_salary'],
      dtype='str')

In [6]:
jobs['remote_allowed'] = jobs['remote_allowed'].fillna("No")
jobs['remote_allowed'] = jobs['remote_allowed'].replace(1,"Yes")

In [17]:
jobs

,title,max_salary,pay_period,location,views,min_salary,formatted_work_type,applies,remote_allowed,application_type,expiry,formatted_experience_level,listed_time,work_type,currency,compensation_type,normalized_salary,posting_date,posting_time
0,Marketing Coordinator,20.0,HOURLY,"Princeton, NJ",20.0,17.0,Full-time,2.0,No,ComplexOnsiteApply,1.715990e+12,NaN,1.713400e+12,FULL_TIME,USD,BASE_SALARY,38480.0,2024-04-18,00:26:40
1,Mental Health Therapist/Counselor,50.0,HOURLY,"Fort Collins, CO",1.0,30.0,Full-time,NaN,No,ComplexOnsiteApply,1.715450e+12,NaN,1.712860e+12,FULL_TIME,USD,BASE_SALARY,83200.0,2024-04-11,18:26:40
2,Assitant Restaurant Manager,65000.0,YEARLY,"Cincinnati, OH",8.0,45000.0,Full-time,NaN,No,ComplexOnsiteApply,1.715870e+12,NaN,1.713280e+12,FULL_TIME,USD,BASE_SALARY,55000.0,2024-04-16,15:06:40
3,Senior Elder Law / Trusts and Estates Associat...,175000.0,YEARLY,"New Hyde Park, NY",16.0,140000.0,Full-time,NaN,No,ComplexOnsiteApply,1.715490e+12,NaN,1.712900e+12,FULL_TIME,USD,BASE_SALARY,157500.0,2024-04-12,05:33:20
4,Service Technician,80000.0,YEARLY,"Burlington, IA",3.0,60000.0,Full-time,NaN,No,ComplexOnsiteApply,1.716040e+12,NaN,1.713450e+12,FULL_TIME,USD,BASE_SALARY,70000.0,2024-04-18,14:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123844,Title IX/Investigations Attorney,195000.0,YEARLY,"Walnut Creek, CA",1.0,120000.0,Full-time,NaN,No,ComplexOnsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,USD,BASE_SALARY,157500.0,2024-04-19,23:40:00
123845,"Staff Software Engineer, ML Serving Platform",NaN,NaN,United States,3.0,NaN,Full-time,NaN,Yes,OffsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,NaN,NaN,NaN,2024-04-19,23:40:00
123846,"Account Executive, Oregon/Washington",NaN,NaN,"Spokane, WA",3.0,NaN,Full-time,NaN,Yes,OffsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,NaN,NaN,NaN,2024-04-19,23:40:00
123847,Business Development Manager,NaN,NaN,"Texas, United States",4.0,NaN,Full-time,NaN,Yes,ComplexOnsiteApply,1.716160e+12,NaN,1.713570e+12,FULL_TIME,NaN,NaN,NaN,2024-04-19,23:40:00
123848,Marketing Social Media Specialist,75000.0,YEARLY,"San Juan Capistrano, CA",2.0,70000.0,Full-time,NaN,No,ComplexOnsiteApply,1.716160e+12,Mid-Senior level,1.713570e+12,FULL_TIME,USD,BASE_SALARY,72500.0,2024-04-19,23:40:00

In [12]:
jobs['posting_date'] = pd.to_datetime(jobs['original_listed_time'], unit='ms').dt.date
jobs['posting_time'] = pd.to_datetime(jobs['original_listed_time'], unit='ms').dt.time

In [15]:
jobs.drop('original_listed_time',axis=1, inplace=True)